/**
 * Unified CLI generator for k6 scripts supporting api, browser and hybrid modes.
 *
 * Selects the generation mode via the `--type` flag (`api` | `browser` |
 * `hybrid` | `all`) and dispatches to the k6 API generator and/or the k6
 * browser generator, writing the resulting scripts under
 * `performance_scripts/k6/`. Run via `npm run k6:generate` (or its
 * `:api`/`:browser`/`:hybrid`/`:all` variants).
 *
 * @packageDocumentation
 */
import { type Scenario, type StepData } from '../src';
import { ScenarioType } from '../src';
import {
  loadAllScenarios,
  toValidFunctionName,
  generateScenarioExecutionCode,
  emitBrowserRuntimeHelpers,
  emitBrowserStepInstructions,
  emitK6BrowserScenarioSetup,
  emitK6BrowserSharedIterationsOptions,
  emitSimpleScenarioBannerHelper,
  generateK6ApiStepBlock,
} from './shared';
import { generateK6Script } from './generate-k6';
import { generateScript as generateK6BrowserScript } from './generate-k6-browser';
import * as fs from 'fs';
import { pathToFileURL } from 'url';
import { k6GeneratorRegistry } from '../src';
import type { K6GeneratorContext, K6StepGenerator } from '../src';
import { config } from '../src';
import { escapeJsString, setNestedValueCode } from '../src';
import { getStepInstanceName } from '../src';
import type { BrowserAdditionalData } from '../src';

function printHelp(): void {
  console.log('k6 unified generator help');
  console.log('');
  console.log('Usage:');
  console.log('  npm run k6:generate');
  console.log('  npm run k6:generate -- -h');
  console.log('  npm run k6:generate -- --help');
  console.log('');
  console.log('Options:');
  console.log('  --type [api|browser|hybrid|all]  Specify which type of scenarios to generate');
  console.log('  --help, -h                       Show this help');
  console.log('');
  console.log('What this generator does:');
  console.log('  - loads all JSON scenarios from tests/scenarios');
  console.log('  - by default, generates all three types of scripts');
  console.log('');
  console.log('Run-time environment variables (used by k6 run):');
  console.log('  K6_SCENARIO_INDEX               Choose one API scenario by index (default: 0 = run all)');
  console.log('  K6_BROWSER_SCENARIO_INDEX       Choose one browser scenario by index (default: 0 = run all)');
  console.log('  K6_HYBRID_SCENARIO_INDEX        Choose one hybrid scenario by index (default: 0 = run all)');
  console.log('  K6_VUS                          Number of VUs (default: 5)');
  console.log('  K6_BROWSER_VUS                  Number of browser VUs (default: 1)');
  console.log('  K6_BROWSER_ITERATIONS           Browser iterations count (default: 1)');
  console.log('  K6_BROWSER_MAX_DURATION         Browser max scenario duration (default: 10m)');
  console.log('  K6_BROWSER_BASE_URL             Browser fallback base URL');
  console.log("  K6_BROWSER_SCREENSHOTS          Browser screenshots switch: 'on' | 'off' (default: on)");
  console.log('');
  console.log('Examples:');
  console.log('  npm run k6:generate');
  console.log('  npm run k6:generate -- --type api');
  console.log('  npm run k6:generate -- --type browser');
  console.log('  npm run k6:generate -- --type hybrid');
  console.log('  npm run k6:generate -- --type all');
}

type GenerationType = 'api' | 'browser' | 'hybrid' | 'all';

function classifyScenario(scenario: Scenario): GenerationType {
  const hasApiSteps: boolean = scenario.steps.some(
    (step: StepData): boolean =>
      step.stepType === ScenarioType.CALCULATOR || step.stepType === ScenarioType.AUTHORIZED_CALCULATOR
  );
  const hasBrowserSteps: boolean = scenario.steps.some(
    (step: StepData): boolean => step.stepType === ScenarioType.BROWSER
  );

  if (hasApiSteps && hasBrowserSteps) {
    return 'hybrid';
  } else if (hasApiSteps) {
    return 'api';
  } else if (hasBrowserSteps) {
    return 'browser';
  }
  return 'api';
}

function generateHybridScript(scenarios: Scenario[]): string {
  const lines: string[] = [];

  const emit: (line?: string) => number = (line: string = ''): number => lines.push(line);

  emit('// performance_scripts/k6/hybrid-performance-test.js — GENERATED FILE');
  emit('// Generated by scripts/generate-k6-unified.ts');
  emit('// Do not edit manually. Re-generate with: npm run k6:generate');
  emit('');
  emit("import http from 'k6/http';");
  emit("import { check, sleep, group } from 'k6';");
  emit("import { Rate, Trend, Counter } from 'k6/metrics';");
  emit("import { browser } from 'k6/browser';");
  emit('');
  emit('// Custom metrics');
  emit("const errorRate = new Rate('errors');");
  emit("const responseTime = new Trend('response_time_ms');");
  emit("const totalRequests = new Counter('total_requests');");
  emit("const AUTH_TOKEN = __ENV.AUTH_TOKEN || '';");
  emit(`const HOSTS = ${JSON.stringify(config.hosts || {})};`);
  emit('');

  emitBrowserRuntimeHelpers(emit, false);
  emitSimpleScenarioBannerHelper(emit, 'FunPerf - k6 Hybrid Scenario', 'stepCount');

  emitK6BrowserSharedIterationsOptions(emit, 'hybrid');

  const hybridScenarios: Scenario[] = scenarios.filter((s) => classifyScenario(s) === 'hybrid');
  const fnNames: string[] = [];
  const scenarioMetadata: { index: number; name: string; stepCount: number }[] = [];

  for (let i = 0; i < hybridScenarios.length; i++) {
    const scenario: Scenario = hybridScenarios[i];
    const fnName: string = toValidFunctionName(`hybrid_${scenario.scenarioName}`);
    fnNames.push(fnName);
    scenarioMetadata.push({ index: i + 1, name: scenario.scenarioName, stepCount: scenario.steps.length });

    emit(`async function ${fnName}() {`);
    emit(`  printScenarioBanner(${i + 1}, '${escapeJsString(scenario.scenarioName)}', ${scenario.steps.length});`);
    emitK6BrowserScenarioSetup(emit, false);
    emit('  try {');

    const preambleCtx: K6GeneratorContext = {
      declaredAttachments: new Set(),
      stepVarName: (_i: number): string => 'step',
      stepInstanceHostRefs: new Map<string, string>(),
    };

    const resDecls: string = scenario.steps.map((_: StepData, s: number): string => `res${s}`).join(', ');
    emit(`    let ${resDecls};`);
    emit('');

    for (let s = 0; s < scenario.steps.length; s++) {
      const step: StepData = scenario.steps[s];
      emit('    {');

      if (step.stepType === ScenarioType.BROWSER) {
        const stepName = step.stepName || `Step ${s + 1}`;
        const stepInstanceName = getStepInstanceName(step);
        const additionalData = step.additionalData as BrowserAdditionalData | undefined;
        if (additionalData?.instructions) {
          emit(`      console.log('Step: ${escapeJsString(stepName)} [${escapeJsString(stepInstanceName)}]');`);
          emit(`      const page = await getPageForStepInstance('${escapeJsString(stepInstanceName)}');`);
          emit('      const browserStepStart = Date.now();');
          emit('      const extractedValues = {};');
          emitBrowserStepInstructions(additionalData, step, stepName, s, emit, '      ');
          emit(
            `      res${s} = { status: ${step.returnCode}, body: JSON.stringify({ currentUrl: page.url(), extracted: extractedValues }), timings: { duration: Date.now() - browserStepStart } };`
          );
        }
      } else {
        const gen: K6StepGenerator | undefined = k6GeneratorRegistry.get(step.stepType);
        if (gen) {
          for (const line of generateK6ApiStepBlock(step, s, scenario.steps, gen, preambleCtx, {
            blockIndent: '    ',
            innerIndent: '      ',
            stepCommentIndent: '      ',
            includeBlockScope: false,
            includeTrailingBlockEnd: false,
            checkIndent: '      ',
            useSetNestedValueCode: true,
            setNestedValueCode,
            preferSourceReferences: true,
            fallbackToGeneratorModification: true,
          })) {
            emit(line);
          }
        } else {
          emit(`      // Step ${s}: "${step.stepName || step.stepType}" — SKIPPED (no generator)`);
        }
      }

      emit('    }');
      emit('');
    }

    emit('  } finally {');
    emit('    await browserContext.close();');
    emit('  }');
    emit('}');
    emit('');
  }

  emit('export default async function () {');
  if (fnNames.length === 0) {
    emit("  console.warn('No HYBRID scenarios found.');");
  } else {
    emit(`  const scenarios = [${fnNames.join(', ')}];`);
    emit(`  const scenarioMetadata = ${JSON.stringify(scenarioMetadata)};`);
    emit("  const index = parseInt(__ENV.K6_HYBRID_SCENARIO_INDEX || '0');");
    for (const line of generateScenarioExecutionCode('scenarios', 'scenarioMetadata', 'index')) {
      emit(line);
    }
  }
  emit('  sleep(1);');
  emit('}');

  return lines.join('\n');
}

function main(): void {
  try {
    const args = process.argv.slice(2);
    if (args.includes('-h') || args.includes('--help') || args.includes('-help')) {
      printHelp();
      return;
    }

    let generationType: GenerationType = 'all';
    const typeArgIndex = args.indexOf('--type');
    if (typeArgIndex !== -1 && typeArgIndex + 1 < args.length) {
      const typeValue = args[typeArgIndex + 1];
      if (['api', 'browser', 'hybrid', 'all'].includes(typeValue)) {
        generationType = typeValue as GenerationType;
      }
    }

    const scenariosDir = 'tests/scenarios';
    const fileToScenarios: Map<string, Scenario[]> = loadAllScenarios(scenariosDir);
    const scenarios: Scenario[] = Array.from(fileToScenarios.values()).flat();

    const outDir = 'performance_scripts/k6';
    if (!fs.existsSync(outDir)) {
      fs.mkdirSync(outDir, { recursive: true });
    }

    if (generationType === 'api' || generationType === 'all') {
      const apiScenarios = scenarios.filter((s) => classifyScenario(s) === 'api');
      const apiScript = generateK6Script(apiScenarios);
      const apiPath = `${outDir}/performance-test.js`;
      fs.writeFileSync(apiPath, apiScript, 'utf-8');
      console.log(`✓ Generated API script: ${apiPath}`);
      console.log(`API scenarios available (${apiScenarios.length}):`);
      apiScenarios.forEach((scenario, idx) => {
        const apiSteps = scenario.steps.filter(
          (step) => step.stepType === ScenarioType.CALCULATOR || step.stepType === ScenarioType.AUTHORIZED_CALCULATOR
        ).length;
        console.log(`  [${idx + 1}] "${scenario.scenarioName}" (${apiSteps} API step(s))`);
      });
      console.log('');
    }

    if (generationType === 'browser' || generationType === 'all') {
      const browserScenarios = scenarios.filter((s) => classifyScenario(s) === 'browser');
      const browserScript = generateK6BrowserScript(browserScenarios);
      const browserPath = `${outDir}/browser-performance-test.js`;
      fs.writeFileSync(browserPath, browserScript, 'utf-8');
      console.log(`✓ Generated browser script: ${browserPath}`);
      console.log(`Browser scenarios available (${browserScenarios.length}):`);
      browserScenarios.forEach((scenario, idx) => {
        const browserSteps = scenario.steps.filter((step) => step.stepType === ScenarioType.BROWSER).length;
        console.log(`  [${idx + 1}] "${scenario.scenarioName}" (${browserSteps} browser step(s))`);
      });
      console.log('');
    }

    if (generationType === 'hybrid' || generationType === 'all') {
      const hybridScenarios = scenarios.filter((s) => classifyScenario(s) === 'hybrid');
      const hybridScript = generateHybridScript(hybridScenarios);
      const hybridPath = `${outDir}/hybrid-performance-test.js`;
      fs.writeFileSync(hybridPath, hybridScript, 'utf-8');
      console.log(`✓ Generated hybrid script: ${hybridPath}`);
      console.log(`Hybrid scenarios available (${hybridScenarios.length}):`);
      hybridScenarios.forEach((scenario, idx) => {
        const apiSteps = scenario.steps.filter(
          (step) => step.stepType === ScenarioType.CALCULATOR || step.stepType === ScenarioType.AUTHORIZED_CALCULATOR
        ).length;
        const browserSteps = scenario.steps.filter((step) => step.stepType === ScenarioType.BROWSER).length;
        console.log(`  [${idx + 1}] "${scenario.scenarioName}" (${apiSteps} API, ${browserSteps} browser step(s))`);
      });
      console.log('');
    }

    console.log('Run with:');
    if (generationType === 'api' || generationType === 'all') {
      console.log(`  npm run k6:run`);
    }
    if (generationType === 'browser' || generationType === 'all') {
      console.log(`  npm run k6:browser:run`);
    }
    if (generationType === 'hybrid' || generationType === 'all') {
      console.log(`  npm run k6:hybrid:run`);
    }
  } catch (error) {
    console.error('Failed to generate k6 scripts:', error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  main();
}
