/**
 * CLI generator producing a k6 browser performance script for UI scenarios.
 *
 * Loads scenarios, keeps only those containing BROWSER steps and emits a
 * self-contained JavaScript file to
 * `performance_scripts/k6/browser-performance-test.js`. Run via
 * `npm run k6:browser:generate`.
 *
 * @packageDocumentation
 */
import { type Scenario, type StepData } from '../src';
import { ScenarioType } from '../src';
import {
  emitBrowserRuntimeHelpers,
  emitBrowserStepInstructions,
  emitK6BrowserScenarioSetup,
  emitK6BrowserSharedIterationsOptions,
  emitSimpleScenarioBannerHelper,
  loadAllScenarios,
  toValidFunctionName,
  generateScenarioExecutionCode,
} from './shared';
import type { BrowserAdditionalData } from '../src';
import { escapeJsString } from '../src';
import * as fs from 'fs';
import { pathToFileURL } from 'url';
import { getStepInstanceName } from '../src';
import { config } from '../src';

function printHelp(): void {
  console.log('k6/browser generator help');
  console.log('');
  console.log('Usage:');
  console.log('  npm run k6:browser:generate');
  console.log('  npm run k6:browser:generate -- -h');
  console.log('  npm run k6:browser:generate -- --help');
  console.log('');
  console.log('What this generator does:');
  console.log('  - loads all JSON scenarios from tests/scenarios');
  console.log('  - keeps only scenarios containing BROWSER steps');
  console.log('  - generates performance_scripts/k6/browser-performance-test.js');
  console.log('');
  console.log('Run-time environment variables (used by k6 run):');
  console.log('  K6_BROWSER_SCENARIO_INDEX   Choose one generated scenario by index (default: 0 = run all)');
  console.log('  K6_BROWSER_VUS              Number of VUs (default: 1)');
  console.log('  K6_BROWSER_ITERATIONS       Iterations count (default: 1)');
  console.log('  K6_BROWSER_MAX_DURATION     Max scenario duration (default: 10m)');
  console.log('  K6_BROWSER_BASE_URL         Fallback base URL when step has no additionalData.baseUrl');
  console.log("  K6_BROWSER_SCREENSHOTS      Global screenshots switch: 'on' (default) | 'off'");
  console.log('');
  console.log('Examples:');
  console.log('  npm run k6:browser:generate');
  console.log('  K6_BROWSER_SCENARIO_INDEX=2 npm run k6:browser:run');
  console.log('  K6_BROWSER_VUS=5 K6_BROWSER_ITERATIONS=30 K6_BROWSER_MAX_DURATION=20m npm run k6:browser:run');
  console.log('  K6_BROWSER_SCREENSHOTS=off npm run k6:browser:run');
  console.log('  K6_BROWSER_BASE_URL=https://playwright.dev npm run k6:browser:run');
}

/**
 * Generates a complete k6 browser performance script for the browser scenarios
 * among the provided list.
 *
 * Emits imports, options, browser runtime helpers, per-scenario functions and
 * the default export wiring them together, translating every browser
 * instruction via the registered browser generator.
 *
 * @param scenarios - Scenarios to filter and include in the generated script.
 * @returns The generated k6 JavaScript source as a string.
 */
export function generateScript(scenarios: Scenario[]): string {
  const browserScenarios: Scenario[] = scenarios.filter(
    (scenario: Scenario): boolean =>
      scenario.steps.some((step: StepData): boolean => step.stepType === ScenarioType.BROWSER) &&
      scenario.steps.every((step: StepData): boolean => step.stepType === ScenarioType.BROWSER)
  );

  const lines: string[] = [];
  const emit: (line?: string) => void = (line: string = ''): void => {
    lines.push(line);
  };

  emit('// performance_scripts/k6/browser-performance-test.js — GENERATED FILE');
  emit('// Generated by scripts/generate-k6-browser.ts');
  emit('// Do not edit manually. Re-generate with: npm run k6:browser:generate');
  emit('');
  emit('import { browser } from "k6/browser";');
  emit('import { check, sleep, group } from "k6";');
  emit('');
  emit(`const HOSTS = ${JSON.stringify(config.hosts || {})};`);
  emit('');
  emitK6BrowserSharedIterationsOptions(emit, 'browser');

  emitBrowserRuntimeHelpers(emit, true);
  emitSimpleScenarioBannerHelper(emit, 'FunPerf - k6 Browser Scenario', 'stepCount');

  const fnNames: string[] = [];
  const scenarioMetadata: { index: number; name: string; stepCount: number }[] = [];

  for (let i = 0; i < browserScenarios.length; i++) {
    const scenario: Scenario = browserScenarios[i];
    const fnName: string = toValidFunctionName(`browser_${scenario.scenarioName}`);
    fnNames.push(fnName);
    const browserStepCount: number = scenario.steps.filter(
      (step: StepData): boolean => step.stepType === ScenarioType.BROWSER
    ).length;
    scenarioMetadata.push({ index: i + 1, name: scenario.scenarioName, stepCount: browserStepCount });

    emit(`async function ${fnName}() {`);
    emit(`  printScenarioBanner(${i + 1}, '${escapeJsString(scenario.scenarioName)}', ${browserStepCount});`);
    emitK6BrowserScenarioSetup(emit, true);
    emit('  try {');

    for (let s = 0; s < scenario.steps.length; s++) {
      const step: StepData = scenario.steps[s];
      if (step.stepType !== ScenarioType.BROWSER) continue;
      const stepName: string = step.stepName || `Step ${s + 1}`;
      const stepInstanceName: string = getStepInstanceName(step);
      const additionalData = step.additionalData as BrowserAdditionalData | undefined;
      if (!additionalData?.instructions) continue;

      emit('    {');
      emit(`      console.log('Step: ${escapeJsString(stepName)} [${escapeJsString(stepInstanceName)}]');`);
      emit(`      const page = await getPageForStepInstance('${escapeJsString(stepInstanceName)}');`);
      emit('      const ctxBefore = Object.assign({}, ctx);');
      emitBrowserStepInstructions(additionalData, step, stepName, s, emit, '      ');
      if (step.dataHandlerName) {
        emit('      const extractedValues = {};');
        emit('      for (const key of Object.keys(ctx)) {');
        emit('        if (ctxBefore[key] !== ctx[key]) extractedValues[key] = ctx[key];');
        emit('      }');
        emit(
          `      stepData['${escapeJsString(step.dataHandlerName)}'] = { request: { instructionsCount: ${additionalData.instructions.length} }, response: { currentUrl: page.url(), extracted: extractedValues } };`
        );
      }
      emit('    }');
      emit('');
    }

    emit('  } finally {');
    emit('    await browserContext.close();');
    emit('  }');
    emit('}');
    emit('');
  }

  emit('export default async function () {');
  if (fnNames.length === 0) {
    emit("  console.warn('No BROWSER scenarios found.');");
  } else {
    emit(`  const scenarios = [${fnNames.join(', ')}];`);
    emit(`  const scenarioMetadata = ${JSON.stringify(scenarioMetadata)};`);
    emit("  const index = parseInt(__ENV.K6_BROWSER_SCENARIO_INDEX || '0');");
    for (const line of generateScenarioExecutionCode('scenarios', 'scenarioMetadata', 'index')) {
      emit(line);
    }
  }
  emit('  sleep(1);');
  emit('}');

  return lines.join('\n');
}

function main(): void {
  try {
    const args: string[] = process.argv.slice(2);
    if (args.includes('-h') || args.includes('--help') || args.includes('-help')) {
      printHelp();
      return;
    }
    const scenariosDir = 'tests/scenarios';
    const fileToScenarios: Map<string, Scenario[]> = loadAllScenarios(scenariosDir);
    const scenarios: Scenario[] = Array.from(fileToScenarios.values()).flat();
    const browserScenarios: Scenario[] = scenarios.filter((scenario: Scenario): boolean => {
      const hasBrowserStep: boolean = scenario.steps.some(
        (step: StepData): boolean => step.stepType === ScenarioType.BROWSER
      );
      if (!hasBrowserStep) {
        console.log(`  ⚠️ Scenario "${scenario.scenarioName}" skipped (no BROWSER type steps)`);
        return false;
      }

      const nonBrowserSteps: StepData[] = scenario.steps.filter(
        (step: StepData): boolean => step.stepType !== ScenarioType.BROWSER
      );
      if (nonBrowserSteps.length > 0) {
        console.log(
          `  ⚠️ Scenario "${scenario.scenarioName}" skipped (mixed step types: ${nonBrowserSteps.length} step(s) not of type BROWSER)`
        );
        return false;
      }

      return true;
    });
    const script: string = generateScript(scenarios);

    const outDir = 'performance_scripts/k6';
    const outPath = `${outDir}/browser-performance-test.js`;
    if (!fs.existsSync(outDir)) {
      fs.mkdirSync(outDir, { recursive: true });
    }

    fs.writeFileSync(outPath, script, 'utf-8');
    console.log(`✓ Generated: ${outPath}`);
    console.log('Run with:');
    console.log(`  k6 run ${outPath}`);
    console.log(`  K6_BROWSER_SCENARIO_INDEX=1 k6 run ${outPath}`);
    console.log('');
    console.log(`Browser scenarios available (${browserScenarios.length}):`);
    browserScenarios.forEach((scenario: Scenario, idx: number): void => {
      const browserSteps: number = scenario.steps.filter(
        (step: StepData): boolean => step.stepType === ScenarioType.BROWSER
      ).length;
      console.log(`  [${idx + 1}] "${scenario.scenarioName}" (${browserSteps} browser step(s))`);
    });
  } catch (error) {
    console.error('Failed to generate k6/browser script:', error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  main();
}
