import {type Scenario, type StepData} from '../src/scenario/loader';
import {k6GeneratorRegistry} from '../src/k6/registry';
import type {K6GeneratorContext, K6StepGenerator} from '../src/k6/interface';
import {config} from '../src/config';
import {escapeJsString} from '../src/k6/common';
import {
  buildDataHandlerMap,
  emitScenarioMetadata,
  isStepDataReference,
  loadAllScenarios,
  parseStepDataReference
} from './shared';
import * as fs from 'fs';

const CALC_BASE_URL: string = config.calculator.url;

function toValidFunctionName(name: string): string {
    let fn: string = name
        .replace(/[^a-zA-Z0-9_]/g, '_')
        .replace(/^_+|_+$/g, '');
    if (/^[0-9]/.test(fn)) {
        fn = 'scenario_' + fn;
    }
    return fn || 'scenario';
}

function generateStepDataRead(resVarName: string, jsonPath: string): string {
    const cleanPath: string = jsonPath.replace(/^\$\./, '');
    const keys: string[] = cleanPath.split('.');
    const chain: string = keys.map((k: string): string => `?.['${k}']`).join('');
    return `JSON.parse(${resVarName}.body)${chain}`;
}

function generateK6Script(scenarios: Scenario[]): string {
    const lines: string[] = [];

    const emit: (line?: string) => number = (line: string = ''): number => lines.push(line);

    // ── Header ──
    emit('// scripts/performance-test.js — GENERATED FILE');
    emit('// Generated by scripts/generate-k6.ts');
    emit('// Do not edit manually. Re-generate with: npm run k6:generate');
    emit('');
    emit("import http from 'k6/http';");
    emit("import { check, sleep, group } from 'k6';");
    emit("import { Rate, Trend, Counter } from 'k6/metrics';");
    emit('');
    emit('// Custom metrics');
    emit('const errorRate = new Rate(\'errors\');');
    emit('const responseTime = new Trend(\'response_time_ms\');');
    emit('const totalRequests = new Counter(\'total_requests\');');
    emit('');
    emit("const AUTH_TOKEN = __ENV.AUTH_TOKEN || '';");
    emit(`const CALC_BASE_URL = __ENV['calculator.url'] || '${CALC_BASE_URL}';`);
    emit('');

    // ── Options ──
    emit('export const options = {');
    emit('  stages: [');
    emit(`    { duration: '30s', target: parseInt(__ENV.K6_VUS || '5') },`);
    emit(`    { duration: '1m', target: parseInt(__ENV.K6_VUS || '5') },`);
    emit(`    { duration: '30s', target: 0 },`);
    emit('  ],');
    emit('  thresholds: {');
    emit(`    http_req_duration: ['p(95)<10000'],`);
    emit(`    http_req_failed: ['rate<0.01'],`);
    emit("    errors: ['rate<0.01'],");
    emit('  },');
    emit('};');
    emit('');

    const preambleCtx: K6GeneratorContext = {
        declaredAttachments: new Set(),
        stepVarName: (_i: number): string => 'step'
    };

    // ── Preamble (attachments) ──
    const preambleLines: string[] = [];
    for (const scenario of scenarios) {
        for (const step of scenario.steps) {
            const gen: K6StepGenerator | undefined = k6GeneratorRegistry.get(step.stepType);
            if (!gen || !gen.generatePreamble) continue;
            preambleLines.push(...gen.generatePreamble(step, preambleCtx));
        }
    }
    const uniquePreamble: string[] = [...new Set(preambleLines)];
    if (uniquePreamble.length > 0) {
        emit('// Pre-load attachment files (k6 open() must be at top level)');
        for (const line of uniquePreamble) {
            emit(line);
        }
        emit('');
    }

    const functionNames: string[] = [];

    // ── Scenario functions ──
    for (let si: number = 0; si < scenarios.length; si++) {
        const scenario: Scenario = scenarios[si];
        const fnName: string = toValidFunctionName(`scenario_${scenario.scenarioName}`);

        const supportedSteps: StepData[] = scenario.steps.filter((s: StepData) => k6GeneratorRegistry.has(s.stepType));
        if (supportedSteps.length === 0) {
            emit(`// Scenario ${si}: "${scenario.scenarioName}" — SKIPPED (no supported step types)`);
            emit(`function ${fnName}() { /* no supported steps */ }`);
            emit('');
            continue;
        }

        const dataHandlerMap: Map<string, number> = buildDataHandlerMap(scenario.steps);

        emit(`// ── Scenario ${si}: "${scenario.scenarioName}" ──`);
        emit(`function ${fnName}() {`);
        const resDecls: string = scenario.steps.map((_: StepData, i: number): string => `res${i}`).join(', ');
        emit(`  let ${resDecls};`);
        emit('');

        const stepBlocks: string[] = [];

        for (let siStep: number = 0; siStep < scenario.steps.length; siStep++) {
            const step: StepData = scenario.steps[siStep];
            const gen: K6StepGenerator | undefined = k6GeneratorRegistry.get(step.stepType);

            if (!gen) {
                stepBlocks.push(`  // Step ${siStep}: "${step.stepName || step.stepType}" — SKIPPED (no generator)`);
                continue;
            }

            const payloadVarName: string = `payload${siStep}`;
            const resVarName: string = `res${siStep}`;
            const blockLines: string[] = [];

            blockLines.push(`  // Step ${siStep}: ${step.stepName || step.stepType}`);
            blockLines.push(`  { // block scope for step ${siStep}`);

            const {code: payloadCode} = gen.generateDefaultPayload(step, {
                declaredAttachments: preambleCtx.declaredAttachments,
                stepVarName: (i: number) => `step${i}`
            });

            for (const line of payloadCode) {
                const renamed: string = line
                    .replace(/\bconst payload\b/g, `const ${payloadVarName}`)
                    .replace(/\blet payload\b/g, `let ${payloadVarName}`);
                blockLines.push(`    ${renamed}`);
            }

            if (step.modifyRequests && step.modifyRequests.length > 0) {
                blockLines.push(`    // Apply modifications`);
                for (const mod of step.modifyRequests) {
                    if (isStepDataReference(mod.modifiedValue)) {
                        const ref: {
                            dataHandlerName: string;
                            jsonPath: string
                        } | null = parseStepDataReference(mod.modifiedValue);
                        if (ref && dataHandlerMap.has(ref.dataHandlerName)) {
                            const sourceStepIdx: number = dataHandlerMap.get(ref.dataHandlerName)!;
                            const sourceResVar: string = `res${sourceStepIdx}`;
                            const readExpr: string = generateStepDataRead(sourceResVar, ref.jsonPath);

                            if ('jsonPath' in mod) {
                                const cleanPath: string = mod.jsonPath.replace(/^\$\./, '');
                                const keys: string[] = cleanPath.split('.');
                                if (keys.length === 1) {
                                    blockLines.push(`    ${payloadVarName}.${keys[0]} = ${readExpr};`);
                                } else {
                                    const access: string = keys.map((k: string) => `['${k}']`).join('');
                                    blockLines.push(`    ${payloadVarName}${access} = ${readExpr};`);
                                }
                            } else if ('modifiedParameter' in mod) {
                                blockLines.push(`    ${payloadVarName}.${mod.modifiedParameter} = ${readExpr};`);
                            }
                            continue;
                        }
                    }

                    const modLines: string[] = gen.generateModification(mod, payloadVarName, step, {
                        declaredAttachments: preambleCtx.declaredAttachments,
                        stepVarName: (i: number): string => `step${i}`
                    });
                    blockLines.push(...modLines.map(l => `    ${l}`));
                }
            }

            blockLines.push('');

            const httpLines: string[] = gen.generateHttpCall(payloadVarName, step, {
                declaredAttachments: preambleCtx.declaredAttachments,
                stepVarName: (i: number): string => `step${i}`
            });
            for (const line of httpLines) {
                const renamed: string = line
                    .replace(/\bconst res\b/g, resVarName)
                    .replace(/\bres\./g, `${resVarName}.`)
                    .replace(/JSON\.stringify\(payload\)/g, `JSON.stringify(${payloadVarName})`)
                    .replace(/\bpayload\b(?![\\'":])/g, payloadVarName);
                blockLines.push(`    ${renamed}`);
            }

            blockLines.push(`    totalRequests.add(1);`);
            blockLines.push(`    responseTime.add(${resVarName}.timings.duration);`);
            blockLines.push('');

            const checks: string[] = [];
            checks.push(`  'status is ${step.returnCode}': (r) => r.status === ${step.returnCode}`);

            if (step.validateResponse && step.validateResponse.length > 0) {
                for (const v of step.validateResponse) {
                    const checkLine: string | null = gen.generateValidationCheck(v, resVarName, step, {
                        declaredAttachments: preambleCtx.declaredAttachments,
                        stepVarName: (i: number): string => `step${i}`
                    });
                    if (checkLine) checks.push(checkLine);
                }
            }

            blockLines.push(`    const success${siStep} = check(${resVarName}, {`);
            blockLines.push(checks.join(',\n'));
            blockLines.push(`    });`);
            blockLines.push('');
            blockLines.push(`    errorRate.add(!success${siStep});`);
            blockLines.push(`  } // end step ${siStep}`);

            stepBlocks.push(blockLines.join('\n'));
            stepBlocks.push('');
        }

        emit(stepBlocks.join('\n').trimEnd());
        emit('}');
        emit('');

        functionNames.push(fnName);
    }

    // ── Scenario metadata ──
    emitScenarioMetadata(
        scenarios,
        emit,
        '// Scenario metadata – used for console preview before test run',
        escapeJsString,
        (step: StepData): string => {
            const gen: K6StepGenerator | undefined = k6GeneratorRegistry.get(step.stepType);
            return gen?.getEndpoint?.(step) || `'${escapeJsString(`Unknown step type: ${step.stepType}`)}'`;
        }
    );

    // ── Default export ──
    emit('export default function () {');
    emit(`  const scenarioIndex = parseInt(__ENV.K6_SCENARIO_INDEX || '0');`);

    function emitScenarioPreview(metaExpr: string): void {
        emit("    console.log('');");
        emit("    console.log('='.repeat(60));");
        emit("    console.log('  Performance Test - Scenario Preview');");
        emit("    console.log('='.repeat(60));");
        emit(`    console.log('  Scenario Index: ' + ${metaExpr}.index);`);
        emit(`    console.log('  Scenario Name:  ' + ${metaExpr}.name);`);
        emit(`    console.log('  Total Steps:    ' + ${metaExpr}.steps.length);`);
        emit("    console.log('');");
        emit("    console.log('  Steps:');");
        emit(`    for (let i = 0; i < ${metaExpr}.steps.length; i++) {`);
        emit(`      console.log('    [' + i + '] ' + ${metaExpr}.steps[i].name);`);
        emit(`      console.log('        -> ' + ${metaExpr}.steps[i].url);`);
        emit("    }");
        emit("    console.log('='.repeat(60));");
        emit("    console.log('');");
    }

    if (functionNames.length === 0) {
        emit('  // No scenarios generated');
    } else if (functionNames.length === 1) {
        emit('');
        emit('  if (__VU === 1 && __ITER === 0) {');
        emit('    const meta = SCENARIO_METADATA[0];');
        emitScenarioPreview('meta');
        emit('  }');
        emit('');
        emit(`  group('Scenario 1', () => {`);
        emit(`    ${functionNames[0]}();`);
        emit('  });');
    } else {
        emit('  const fns = [' + functionNames.join(', ') + '];');
        emit('');
        emit('  // Print scenario info once at startup (only first VU, first iteration)');
        emit('  if (__VU === 1 && __ITER === 0) {');
        emit('    if (scenarioIndex === 0) {');
        emit('      // Show all scenarios');
        emit("      console.log('');");
        emit("      console.log('='.repeat(60));");
        emit("      console.log('  FunPerf - Available Scenarios');");
        emit("      console.log('='.repeat(60));");
        emit('      for (let i = 0; i < SCENARIO_METADATA.length; i++) {');
        emit('        const m = SCENARIO_METADATA[i];');
        emit(`        console.log('  [' + m.index + '] ' + m.name + ' (' + m.steps.length + ' step(s))');`);
        emit('      }');
        emit("      console.log('='.repeat(60));");
        emit("      console.log('');");
        emit("      console.log('  Running all scenarios...');");
        emit("      console.log('');");
        emit('    } else if (scenarioIndex > 0 && scenarioIndex <= fns.length) {');
        emit('      const meta = SCENARIO_METADATA[scenarioIndex - 1];');
        emitScenarioPreview('meta');
        emit('    }');
        emit('  }');
        emit('');
        emit('  if (scenarioIndex === 0) {');
        emit('    // Run all scenarios');
        emit('    for (let i = 0; i < fns.length; i++) {');
        emit(`      group('Scenario ' + SCENARIO_METADATA[i].index + ': ' + SCENARIO_METADATA[i].name, () => {`);
        emit('        fns[i]();');
        emit('      });');
        emit('    }');
        emit('  } else if (scenarioIndex > 0 && scenarioIndex <= fns.length) {');
        emit(`    group('Scenario ' + scenarioIndex + ': ' + SCENARIO_METADATA[scenarioIndex - 1].name, () => {`);
        emit('      fns[scenarioIndex - 1]();');
        emit('    });');
        emit('  } else {');
        emit(`    console.error('Invalid K6_SCENARIO_INDEX: ' + scenarioIndex + '. Valid: 0 (all), 1-' + fns.length);`);
        emit('  }');
    }

    emit('  sleep(1);');
    emit('}');

    return lines.join('\n');
}

// ── Main ──
function main(): void {
    try {
        const scenariosDir: string = 'tests/scenarios';
        const scenarios: Scenario[] = loadAllScenarios(scenariosDir);
        console.log(`\nGenerating k6 script for ${scenarios.length} scenario(s) from ${scenariosDir}/...\n`);

        const k6Script: string = generateK6Script(scenarios);
        const outDir: string = 'performance_scripts/k6';
        const outPath: string = `${outDir}/performance-test.js`;

        if (!fs.existsSync(outDir)) {
            fs.mkdirSync(outDir, {recursive: true});
        }
        fs.writeFileSync(outPath, k6Script, 'utf-8');
        console.log(`✓ Generated: ${outPath}\n`);
        console.log('Run with:');
        console.log(`  k6 run ${outPath}`);
        console.log(`  k6 run --out web-dashboard ${outPath}`);
        console.log(`  k6 run --out json=results/perf.json ${outPath}\n`);

        for (let i: number = 0; i < scenarios.length; i++) {
            const s: Scenario = scenarios[i];
            const stepCount: number = s.steps.length;
            const supportedCount: number = s.steps.filter((st: StepData): boolean => k6GeneratorRegistry.has(st.stepType)).length;
            if (supportedCount === 0) {
                console.log(`  [${i + 1}] "${s.scenarioName}": skipped (${stepCount} step(s), no supported step types)`);
                continue;
            }
            console.log(`  [${i + 1}] "${s.scenarioName}": ${stepCount} step(s)`);
        }
    } catch (error) {
        console.error('Failed to generate k6 script:', error instanceof Error ? error.message : String(error));
        process.exit(1);
    }
}

main();
